Update test_and_build_debian_package.yml
Добавил проверку версии

diff --git a/.github/workflows/test_and_build_debian_package.yml b/.github/workflows/test_and_build_debian_package.yml
--- a/.github/workflows/test_and_build_debian_package.yml
+++ b/.github/workflows/test_and_build_debian_package.yml
@@ -10,9 +10,34 @@ on:
       - '*'
 
 jobs:
+  check-version:
+    runs-on: ubuntu-latest
+    outputs:
+      current_version: ${{ steps.get_version.outputs.version }}
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
+      - name: Get current version from setup.py
+        id: get_version
+        run: |
+          VERSION=$(python -c "import re; f = open('setup.py').read(); print(re.search(r'version\\s*=\\s*[\"\\\']([0-9.]+)[\"\\\']', f).group(1))")
+          echo "::set-output name=version::$VERSION"
+
+      - name: Check version against main
+        run: |
+          git fetch origin main
+          MAIN_VERSION=$(git show origin/main:setup.py | python -c "import re, sys; f = sys.stdin.read(); print(re.search(r'version\\s*=\\s*[\"\\\']([0-9.]+)[\"\\\']', f).group(1))")
+          if [ "${{ steps.get_version.outputs.version }}" == "$MAIN_VERSION" ]; then
+            echo "Version has not changed. Failing job."
+            exit 1
+          fi
+          echo "Version has changed. Proceeding."
+          
   test:
     runs-on: ubuntu-latest
-
+    needs: check-version
+    
     steps:
     - name: Checkout repository
       uses: actions/checkout@v3
@@ -41,7 +66,7 @@ jobs:
 
   release:
     runs-on: ubuntu-latest
-    needs: test
+    needs: [check-version, test]
     if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
 
     steps:
@@ -76,12 +101,12 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
         if [ "${{ github.event_name }}" == "pull_request" ]; then
-          version="prv$(python setup.py --version | tr -d '[:space:]')"
+          version="prv${{ needs.check-version.outputs.current_version }}"
           # Delete existing tag if it exists
           git push --delete origin "$version" || true
           git tag -d "$version" || true
         else
-          version="v$(python setup.py --version | tr -d '[:space:]')"
+          version="v${{ needs.check-version.outputs.current_version }}"
         fi
         git config user.name "github-actions[bot]"
         git config user.email "github-actions[bot]@users.noreply.github.com"
