Update test_and_build_debian_package.yml (#26)
Added a version of the version before build.

diff --git a/.github/workflows/test_and_build_debian_package.yml b/.github/workflows/test_and_build_debian_package.yml
--- a/.github/workflows/test_and_build_debian_package.yml
+++ b/.github/workflows/test_and_build_debian_package.yml
@@ -1,4 +1,4 @@
-name: Build and Release
+name: Test, Build and Release
 
 on:
   push:
@@ -10,8 +10,36 @@ on:
       - '*'
 
 jobs:
+  check-version:
+    runs-on: ubuntu-latest
+    outputs:
+      current_version: ${{ steps.get_version.outputs.version }}
+    steps:
+      - name: Check out code
+        uses: actions/checkout@v2
+  
+      - name: Get current version from setup.py
+        id: get_version
+        run: |
+          VERSION=$(python setup.py --version | tr -d '[:space:]')
+          echo "Current version: $VERSION"
+          echo "::set-output name=version::$VERSION"
+  
+      - name: Check version against main
+        run: |
+          git fetch origin main
+          MAIN_VERSION=$(git show origin/main:setup.py | grep -i 'version=' | head -n 1 | sed -E "s/.*version=['\"]([^'\"]+)['\"].*/\1/")
+          echo "Version in main branch: $MAIN_VERSION"
+          echo "Version in current branch: ${{ steps.get_version.outputs.version }}"
+          if [ "${{ steps.get_version.outputs.version }}" == "$MAIN_VERSION" ]; then
+            echo "Version has not changed in setup.py. Failing job."
+            exit 1
+          fi
+          echo "Version has changed in setup.py. Proceeding."
+
   test:
     runs-on: ubuntu-latest
+    needs: check-version
 
     steps:
     - name: Checkout repository
@@ -41,7 +69,7 @@ jobs:
 
   release:
     runs-on: ubuntu-latest
-    needs: test
+    needs: [check-version, test]
     if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
 
     steps:
@@ -63,7 +91,7 @@ jobs:
     - name: Build Debian Package
       id: build_package
       run: |
-        version=$(python setup.py --version | tr -d '[:space:]')
+        version=${{ needs.check-version.outputs.current_version }}
         echo "Building Debian package version $version..."
         fpm -s python -t deb --python-bin python3 --name fastmodbuslibrary --version $version .
 
@@ -76,12 +104,12 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
         if [ "${{ github.event_name }}" == "pull_request" ]; then
-          version="prv${{ github.event.pull_request.number }}"
+          version="prv${{ needs.check-version.outputs.current_version }}"
           # Delete existing tag if it exists
           git push --delete origin "$version" || true
           git tag -d "$version" || true
         else
-          version="v${{ needs.test.outputs.version }}"
+          version="v${{ needs.check-version.outputs.current_version }}"
         fi
         git config user.name "github-actions[bot]"
         git config user.email "github-actions[bot]@users.noreply.github.com"
